export const AUTH_START='AUTH_START';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const USER_TYPE='USER_TYPE';
export const MARKER_LOCATION='MARKER_LOCATION';
export const SUBMISSION='SUBMISSION';